export const englishRoutes = {
    greeting: [
    "hi",
    "hello",
    "hey",
    "hey there",
    "good morning",
    "good evening",
    ],
  guardian_help: [
    "how does the extension work?",
    "what does Guardian do?",
    "how does the system detect harmful comments?",
    "why was this comment blurred?",
    "how can I view a blurred comment?",
    "how do I report harmful content?",
    "what is parental protection mode?",
    "how does the extension protect me online?",
    "how do I install the extension?",
    "can you help me install the extension?",
    "why is this platform useful?",
    "what is the purpose of Guardian?",
    "why do I need this extension?",
    "what can I do on the website?",
    "what features does the platform have?",
    "how do I activate the extension?",
    "where can I download the extension?",
    "where is the download button?",
    "what is on the Join page?",
    "how does the blur feature work?",
    "can I remove the blur?",
    "what happens when a comment is flagged?",
    "how does Guardian decide if a comment is harmful?",
    "does the extension work on YouTube?",
    "does the extension work on Twitter?",
    "what does parental mode do?",
    "can I see comments in parental mode?",
    "does Guardian protect children?",
    "how does the reporting feature work?",
    "how can I see statistics on the website?",
    "does Guardian support Hebrew?",
    "does Guardian support English?",
  ],

  toxicity_check: [
    "is this comment offensive?",
    "someone insulted me online",
    "this comment feels uncomfortable",
    "someone wrote something offensive to me",
    "how do I know if content is toxic?",
    "should I reply to this and how?",
    "someone cursed at me",
    "someone wrote something nasty about me",
    "I received a harmful message",
    "I'm not sure if this is offensive",
    "is this cyberbullying?",
    "is this a curse?",
    "is this humiliation?",
    "is this inappropriate content?",
    "should I report this?",
    "what should I do if I got hurt by a comment?",
    "how to deal with an insulting comment?",
    "should I ignore it or respond?",
    "someone wrote something bad about me on YouTube",
    "someone wrote something bad about me on Twitter",
    "is this sentence toxic?",
    "is this sentence insulting?",
    "is this shaming?",
  ],

  irrelevant: [
    "what is the weather today?",
    "give me a cake recipe",
    "tell me a joke",
    "what is two plus two",
    "sing a song",
    "what is the fastest animal",
    "write me a love song",
    "create a workout plan",
    "what time is it now",
    "who is the prime minister",
    "help me with math homework",
    "write me a resume",
    "recommend me a movie",
    "how to cook pasta",
  ],
};